[project]
name = "rna-vel-pred"
version = "0.1.0"
description = "Add your description here"
readme = "README.rst"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.14",
    "django-experiment-tracker",
    "marimo>=0.23.6",
    "polars[pyarrow]>=1.40.1",
    "scvelo>=0.3.4",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-django>=4.11.1",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "project.settings"
python_files = ["test_*.py", "*_test.py", "tests.py"]

[tool.uv.sources]
django-experiment-tracker = { path = "../django-experiment-tracker", editable = true }
