defaults:
  - Dataset
  - Generated
  - _self_

name: MotifSimple
epsilon: .05
data_dir: ${...data_dir}/${.name}
processed_file_name: sparsify_step_time_${.sparsify_step_time}__num_neighbors_${.num_neighbors}__num_pnts_${.num_pnts}__epsilon_${.epsilon}
