hydra:
  run:
    dir: ${...out_dir}/hydra/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${...out_dir}/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_

root_dir: /home/reepoi/GitHub/velocityPrediction
out_dir: ${.root_dir}/../../out/rna_vel_pred
data_dir: ${.root_dir}/data
rng_seed: 0
wandb:
  entity: taost
  project: rna_vel_pred
  run: null
  dir: ${..out_dir}

# dataset:
#   name: Simple
#   path: ${out_dir}/data/${dataset.name}/${dataset.name}.csv
#   neighbors: slidingwindow
#   num_neighbors: 4
#   num_prev_neighbors: null
#   neighbor_radius: .05
#   batch_size: 2
#   sparsity_step: 11
#   pred_split: val
# model: MLP
# trainer:
#   max_epochs: 100
#   fit: true
#   check_val_every_n_epoch: 1
#   val: false
#   pred: false
#   ckpt: last
#   logger: true
#   devices: 1
#   accelerator: gpu
