out_dir: ../../out/paytonco
rng_seed: 0
dataset:
  name: Simple
  path: ${out_dir}/data/${dataset.name}/${dataset.name}.csv
  neighbors: slidingwindow
  num_neighbors: 4
  num_prev_neighbors: null
  neighbor_radius: .05
  batch_size: 2
  sparsity_step: 11
  pred_split: val
model: MLP
trainer:
  fit: true
  fit_ckpt: null
  predict: true
  pred_ckpt: null
  logger: true
  max_epochs: 100
  default_root_dir: ${out_dir}/ckpts/${dataset.name}/${model}
  ckpt_path: ${out_dir}/ckpts/${dataset.name}
  devices: 1
  accelerator: gpu
  stats: false
