hydra:
  run:
    dir: ${...out_dir}/hydra/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${...out_dir}/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: First
  - /wandb@wandb
  - _self_

root_dir: /home/reepoi/GitHub/velocityPrediction
out_dir: ${.root_dir}/../../out/rna_vel_pred
run_dir: ${.out_dir}/runs
data_dir: ${.root_dir}/data
rng_seed: 0
wandb:
  dir: ${..out_dir}
trainer:
  copy_saved_cfg:
    - dataset
  max_epochs: 100
  fit: true
  check_val_every_n_epoch: 10
  val: false
  test: false
  pred: false
  ckpt: last
  logger: true
  devices: 1
  accelerator: gpu
  batch_size: 10
