out_dir: ../../out/paytonco
dataset:
  name: Simple
  path: ${out_dir}/data/${dataset.name}/${dataset.name}.csv
  num_neighbors: 5
  batch_size: 2
model:
  dim: 2
trainer:
  fit: true
  predict: true
  logger: false
  max_epochs: 10
  default_root_dir: ${out_dir}/ckpts/${dataset.name}
  ckpt_path: ${out_dir}/ckpts/${dataset.name}
  devices: 1
  accelerator: gpu
