hydra:
  run:
    dir: ${...out_dir}/hydra/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${...out_dir}/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_

root_dir: /root/workspace/GitHub/velocityPrediction
out_dir: ${.root_dir}/../../out/rna_vel_pred
plot_dir: ${.out_dir}/plots
data_dir: ${.out_dir}/data_redesign
rng_seed: 0
wandb:
  entity: taost
  project: rna_vel_pred
  dir: ${..out_dir}

fmt: png

run_ids: []
use_umap_2d: false
plot:
  context: poster
  style: white
  dataset:
    do: false
  vel_pred:
    do: false
  mse:
    sparsifier_neighbor_set_heatmap:
      do: false
    umap_dimension:
      do: false
