method: grid
metric:
  name: val_loss
  goal: minimize

parameters:
  dataset.1.data_subdir:
    values: [pancreas, bonemarrow, dentategyrus, forebrain]
  dataset.1.num_neighbors:
    values: [3, 7, 9, 11, 13, 15, 17, 19]
  dataset.1.sparsify_step_time:
    values: [3, 5, 7, 9, 11, 13, 15, 17, 19]

command:
  - ${env}
  - CUDA_VISIBLE_DEVICES=4
  - python3
  - src/main.py
  - model.hidden.layers=9
  - model.hidden.dim=7
  - model.bias=false
  - model.activation=ReLU
  - +dataset@dataset.1=SCVeloSaved
  - dataset.1.umap.n_components=49
  - ${args_no_hyphens}
