method: grid
metric:
  name: val_loss
  goal: minimize

parameters:
  dataset.1.num_neighbors:
    values: [4, 6, 8, 10, 12, 14, 16, 18, 20]
  dataset.1.sparsify_step_time:
    values: [6, 9, 13, 16, 19, 22, 25, 28, 31]

# [ 6.25541126  9.38311688 12.51082251 15.63852814 18.76623377 21.89393939 25.02164502 28.14935065 31.27705628]


command:
  - ${env}
  - CUDA_VISIBLE_DEVICES=5
  - python3
  - src/main.py
  - model=First
  - model.hidden.layers=9
  - model.hidden.dim=7
  - model.bias=false
  - model.activation=ReLU
  - +dataset@dataset.1=SCVeloSaved
  - dataset.1.data_subdir=bonemarrow
  - dataset.1.umap.n_components=49
  - ${args_no_hyphens}
