method: bayes
metric:
  name: val_loss
  goal: minimize

parameters:
  dataset.1.num_neighbors:
    values: [7, 9, 11, 13, 15, 17, 19]
  dataset.1.sparsify_step_time:
    values: [5, 7, 9, 11, 13, 15, 17, 19]
  model.bias:
    values: [true, false]
  model.hidden.dim:
    values: [3, 5, 7, 10, 15, 20, 25, 30]
  model.hidden.layers:
    values: [0, 1, 2, 3, 5, 7, 9, 11]
  model.activation:
    values: [ReLU, Tanh]

command:
  - ${env}
  - CUDA_VISIBLE_DEVICES=0
  - python3
  - src/main.py
  - +dataset@dataset.1=MotifBifurcation
  - ${args_no_hyphens}
