method: grid
metric:
  name: val_loss
  goal: minimize

parameters:
  dataset.1.umap.n_components:
    values: [3, 5, 7, 9, 11, 13, 15, 17, 19, 24, 29, 34, 39, 44, 49, 59, 69, 79, 89, 99]


command:
  - ${env}
  - CUDA_VISIBLE_DEVICES=4
  - python3
  - src/main.py
  - model=First
  - model.hidden.layers=9
  - model.hidden.dim=7
  - model.bias=false
  - model.activation=ReLU
  - +dataset@dataset.1=SCVeloSaved
  - dataset.1.data_subdir=dentategyrus
  - dataset.1.num_neighbors=18
  - dataset.1.sparsify_step_time=12
  - ${args_no_hyphens}
