method: bayes
metric:
  name: val_loss
  goal: minimize

parameters:
  dataset.1.num_neighbors:
    values: [7, 9, 11, 13, 15, 17, 19]
  dataset.1.sparsify_step_time:
    values: [5, 7, 9, 11, 13, 15, 17, 19]
  dataset.1.umap.n_components:
    values: [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]

command:
  - ${env}
  - CUDA_VISIBLE_DEVICES=0
  - python3
  - src/main.py
  - +dataset@dataset.1=SCVeloSaved
  - dataset.1.data_subdir=pancreas
  - ${args_no_hyphens}
