# Generated by Django 5.2.14 on 2026-05-18 16:39

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_experiment_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.CharField(db_default=django.db.models.functions.text.Concat(models.Value('exp_'), django.db.models.functions.text.Lower(models.Func(models.Func(models.Value(4), function='randomblob'), function='hex'))), editable=False, max_length=12, unique=True)),
                ('time_created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('git_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='django_experiment_tracker.gitcommit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentParameter',
            fields=[
                ('pk', models.CompositePrimaryKey('experiment', 'parameter', blank=True, editable=False, primary_key=True, serialize=False)),
                ('parameter_value', models.CharField(max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rna_vel_pred.experiment')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_experiment_tracker.parameter')),
            ],
        ),
    ]
