# Generated by Django 5.2.14 on 2026-08-13 20:31

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_experiment_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.CharField(db_default=django.db.models.functions.text.Concat(models.Value('exp_'), django.db.models.functions.text.Lower(models.Func(models.Func(models.Value(4), function='randomblob'), function='hex'))), editable=False, max_length=12, unique=True)),
                ('time_created', models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now())),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('git_commit_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_related', related_query_name='%(app_label)s_%(class)ss_created', to='django_experiment_tracker.gitcommit')),
                ('git_commit_valid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_valid_for_related', related_query_name='%(app_label)s_%(class)ss_valid_for', to='django_experiment_tracker.gitcommit')),
                ('tags', models.ManyToManyField(blank=True, to='django_experiment_tracker.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedDatasetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.CharField(db_default=django.db.models.functions.text.Concat(models.Value('ds_'), django.db.models.functions.text.Lower(models.Func(models.Func(models.Value(4), function='randomblob'), function='hex'))), editable=False, max_length=11, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('shared_file_name', models.CharField(max_length=100)),
                ('shared_file_description', models.CharField(blank=True, max_length=100)),
                ('git_commit_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_related', related_query_name='%(app_label)s_%(class)ss_created', to='django_experiment_tracker.gitcommit')),
                ('git_commit_valid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_valid_for_related', related_query_name='%(app_label)s_%(class)ss_valid_for', to='django_experiment_tracker.gitcommit')),
                ('tags', models.ManyToManyField(blank=True, to='django_experiment_tracker.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_value', models.CharField(max_length=100)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_vel_pred.experiment')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_experiment_tracker.parameter')),
                ('parameter_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_experiment_tracker.parametergroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('experiment', 'parameter_group', 'parameter'), name='experiment_group_and_parameter_alt_key')],
            },
        ),
        migrations.CreateModel(
            name='SavedDatasetFileParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_value', models.CharField(max_length=100)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_experiment_tracker.parameter')),
                ('parameter_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_experiment_tracker.parametergroup')),
                ('saved_dataset_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_vel_pred.saveddatasetfile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('saved_dataset_file', 'parameter_group', 'parameter'), name='saved_dataset_file_group_and_parameter_alt_key')],
            },
        ),
    ]
